In [ ]:
### Завдання 0
Створити скрипт для завантаження VHI-даних для всіх адміністративних одиниць України (крім вибірки по всій країні, provinceID=0).  
Дані зберігати у папку `data` з додаванням дати та часу у назву файлу.  
Передбачити повторні запуски та уникати повторного завантаження.

In [8]:
import os
import requests
from datetime import datetime

#папка для збереження файлів
save_folder = "data"

#список областей України
ukraine_provinces = list(range(1, 25))

#функція завантаження VHI для однієї області через requests
def download_vhi_requests(province_id, save_folder=save_folder):
    url = f"https://www.star.nesdis.noaa.gov/smcd/emb/vci/VH/get_TS_admin.php?country=UKR&provinceID={province_id}&year1=1981&year2=2024&type=Mean"
    filename = f"VHI_province{province_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    filepath = os.path.join(save_folder, filename)

    if not os.path.exists(filepath):
        # verify=False вимикає перевірку SSL
        r = requests.get(url, verify=False)
        with open(filepath, "wb") as f:
            f.write(r.content)
        print(f"Файл завантажено: {filename}")
    else:
        print(f"Файл для області {province_id} вже існує")
    
    return filepath

#завантажую файли для всіх областей
for province_id in ukraine_provinces:
    download_vhi_requests(province_id)

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province1_20260308_131121.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province2_20260308_131123.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province3_20260308_131124.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province4_20260308_131125.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province5_20260308_131126.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province6_20260308_131127.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province7_20260308_131128.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province8_20260308_131129.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province9_20260308_131130.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province10_20260308_131131.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province11_20260308_131132.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province12_20260308_131133.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province13_20260308_131134.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province14_20260308_131135.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province15_20260308_131136.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province16_20260308_131137.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province17_20260308_131138.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province18_20260308_131139.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province19_20260308_131140.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province20_20260308_131141.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province21_20260308_131142.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province22_20260308_131143.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province23_20260308_131144.txt

/Users/miroslavaromashko/Documents/datascience/lab2/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.star.nesdis.noaa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Файл завантажено: VHI_province24_20260308_131145.txt

In [ ]:
### Завдання 1
Зчитати завантажені текстові файли у pandas DataFrame.  
Очистити дані: прибрати зайві рядки та стовпці, заповнити пропуски, додати номер області та назву.  
Підготувати DataFrame для подальшого аналізу.

In [11]:
import os
import pandas as pd

data_folder = "data"

province_names = {
    1: "Вінницька", 2: "Волинська", 3: "Дніпропетровська", 4: "Донецька",
    5: "Житомирська", 6: "Закарпатська", 7: "Запорізька", 8: "Івано-Франківська",
    9: "Київська", 10: "Кіровоградська", 11: "Луганська", 12: "Львівська",
    13: "Миколаївська", 14: "Одеська", 15: "Полтавська", 16: "Рівненська",
    17: "Сумська", 18: "Тернопільська", 19: "Харківська", 20: "Херсонська",
    21: "Хмельницька", 22: "Черкаська", 23: "Чернівецька", 24: "Чернігівська"
}

files = [f for f in os.listdir(data_folder) if f.endswith(".txt")]
files.sort()

dfs = []

for file in files:
    filepath = os.path.join(data_folder, file)
    province_id = int(file.split("_")[1].replace("province", ""))
    
    #читаю файл, пропускаю перші 2 рядки
    df = pd.read_csv(filepath, sep=",", header=None, skiprows=2, engine='python')
    
    #залишаю тільки рядки з 7 колонками
    df = df[df.columns[:7]]
    
    #задаю назви колонок
    df.columns = ["year", "week", "SMN", "SMT", "VCI", "TCI", "VHI"]
    
    #приводжу числові колонки до float
    df[["SMN","SMT","VCI","TCI","VHI"]] = df[["SMN","SMT","VCI","TCI","VHI"]].apply(pd.to_numeric, errors="coerce")
    
    #додаю інформацію про область
    df["province_id"] = province_id
    df["province_name"] = province_names[province_id]
    
    #видаляю рядки без року
    df = df[pd.to_numeric(df["year"], errors="coerce").notnull()]
    
    dfs.append(df)

#об'єдную все в один DataFrame
vhi_data = pd.concat(dfs, ignore_index=True)

vhi_data.head()

   year  week    SMN     SMT    VCI    TCI    VHI  province_id   province_name
0  1982   2.0  0.063  261.53  55.89  38.20  47.04           10  Кіровоградська
1  1982   3.0  0.063  263.45  57.30  32.69  44.99           10  Кіровоградська
2  1982   4.0  0.061  265.10  53.96  28.62  41.29           10  Кіровоградська
3  1982   5.0  0.058  266.42  46.87  28.57  37.72           10  Кіровоградська
4  1982   6.0  0.056  267.47  39.55  30.27  34.91           10  Кіровоградська

In [ ]:
### Завдання 2
Змінити індекси областей у DataFrame `vhi_data`, щоб вони відповідали українській абетці.

In [13]:
#відповідність українська абетка: index 1-24
ukr_province_order = {
    "Вінницька": 1, "Волинська": 2, "Дніпропетровська": 3, "Донецька": 4,
    "Житомирська": 5, "Закарпатська": 6, "Запорізька": 7, "Івано-Франківська": 8,
    "Київська": 9, "Кіровоградська": 10, "Луганська": 11, "Львівська": 12,
    "Миколаївська": 13, "Одеська": 14, "Полтавська": 15, "Рівненська": 16,
    "Сумська": 17, "Тернопільська": 18, "Харківська": 19, "Херсонська": 20,
    "Хмельницька": 21, "Черкаська": 22, "Чернівецька": 23, "Чернігівська": 24
}

#додаю новий стовпець з індексом за українською абеткою
vhi_data["ukr_index"] = vhi_data["province_name"].map(ukr_province_order)

vhi_data.head()

,year,week,SMN,SMT,VCI,TCI,VHI,province_id,province_name,ukr_index
0,1982,2.0,0.063,261.53,55.89,38.20,47.04,10,Кіровоградська,10
1,1982,3.0,0.063,263.45,57.30,32.69,44.99,10,Кіровоградська,10
2,1982,4.0,0.061,265.10,53.96,28.62,41.29,10,Кіровоградська,10
3,1982,5.0,0.058,266.42,46.87,28.57,37.72,10,Кіровоградська,10
4,1982,6.0,0.056,267.47,39.55,30.27,34.91,10,Кіровоградська,10

In [ ]:
### Завдання 3
Реалізувати функції для отримання:
1. Ряду VHI для конкретної області та року
2. Ряду VHI за діапазон років для кількох областей
3. Пошуку мінімуму, максимуму, середнього та медіани

In [15]:
# 1. VHI для області за конкретний рік
def get_vhi_by_year(province_id, year):
    df = vhi_data[(vhi_data["ukr_index"] == province_id) & (vhi_data["year"] == year)]
    result = df[["week", "VHI"]]
    print(f"VHI для області {province_id} за рік {year}:")
    display(result)
    return result

# 2. VHI за діапазон років для кількох областей
def get_vhi_by_year_range(province_ids, start_year, end_year):
    df = vhi_data[(vhi_data["ukr_index"].isin(province_ids)) & 
                  (vhi_data["year"] >= start_year) & (vhi_data["year"] <= end_year)]
    result = df[["province_name", "year", "week", "VHI"]]
    print(f"VHI для областей {province_ids} з {start_year} по {end_year}:")
    display(result)
    return result

# 3. Статистика (мінімум, максимум, середнє, медіана)
def vhi_statistics(province_ids, start_year, end_year):
    df = get_vhi_by_year_range(province_ids, start_year, end_year)
    stats = df.groupby("province_name")["VHI"].agg(["min","max","mean","median"])
    print(f"Статистика VHI для областей {province_ids} з {start_year} по {end_year}:")
    display(stats)
    return stats

#перетворюю колонку year у int
vhi_data["year"] = pd.to_numeric(vhi_data["year"], errors="coerce")

#приклади виклику функцій

# 1. VHI для області 10 (Кіровоградська) за 1985 рік
get_vhi_by_year(10, 1985)

# 2. VHI для областей 10, 12, 15 за 1985-1986 роки
get_vhi_by_year_range([10, 12, 15], 1985, 1986)

# 3. Статистика VHI для областей 10, 12, 15 за 1985-1986 роки
vhi_statistics([10, 12, 15], 1985, 1986)

VHI для області 10 за рік 1985:

     week    VHI
155   1.0  -1.00
156   2.0  -1.00
157   3.0  -1.00
158   4.0  -1.00
159   5.0  -1.00
160   6.0  -1.00
161   7.0  -1.00
162   8.0  -1.00
163   9.0  47.01
164  10.0  50.10
165  11.0  47.55
166  12.0  45.69
167  13.0  41.92
168  14.0  37.96
169  15.0  33.33
170  16.0  30.89
171  17.0  30.15
172  18.0  30.98
173  19.0  31.77
174  20.0  32.35
175  21.0  37.26
176  22.0  40.02
177  23.0  42.44
178  24.0  48.56
179  25.0  53.22
180  26.0  54.84
181  27.0  56.00
182  28.0  55.58
183  29.0  53.50
184  30.0  50.57
185  31.0  44.44
186  32.0  40.31
187  33.0  36.84
188  34.0  33.94
189  35.0  33.60
190  36.0  35.90
191  37.0  37.99
192  38.0  38.21
193  39.0  39.67
194  40.0  40.36
195  41.0  39.49
196  42.0  40.07
197  43.0  38.79
198  44.0  36.11
199  45.0  35.25
200  46.0  36.49
201  47.0  35.61
202  48.0  37.25
203  49.0  39.66
204  50.0  42.42
205  51.0  44.23
206  52.0  46.37

VHI для областей [10, 12, 15] з 1985 по 1986:

        province_name  year  week    VHI
155    Кіровоградська  1985   1.0  -1.00
156    Кіровоградська  1985   2.0  -1.00
157    Кіровоградська  1985   3.0  -1.00
158    Кіровоградська  1985   4.0  -1.00
159    Кіровоградська  1985   5.0  -1.00
...               ...   ...   ...    ...
11429      Полтавська  1986  48.0  27.13
11430      Полтавська  1986  49.0  29.21
11431      Полтавська  1986  50.0  32.23
11432      Полтавська  1986  51.0  35.23
11433      Полтавська  1986  52.0  39.27

[312 rows x 4 columns]

VHI для областей [10, 12, 15] з 1985 по 1986:

        province_name  year  week    VHI
155    Кіровоградська  1985   1.0  -1.00
156    Кіровоградська  1985   2.0  -1.00
157    Кіровоградська  1985   3.0  -1.00
158    Кіровоградська  1985   4.0  -1.00
159    Кіровоградська  1985   5.0  -1.00
...               ...   ...   ...    ...
11429      Полтавська  1986  48.0  27.13
11430      Полтавська  1986  49.0  29.21
11431      Полтавська  1986  50.0  32.23
11432      Полтавська  1986  51.0  35.23
11433      Полтавська  1986  52.0  39.27

[312 rows x 4 columns]

Статистика VHI для областей [10, 12, 15] з 1985 по 1986:

                min    max       mean  median
province_name
Кіровоградська -1.0  56.00  35.150288  36.215
Львівська      -1.0  63.88  36.462500  38.200
Полтавська     -1.0  51.07  34.973942  38.040

                min    max       mean  median
province_name
Кіровоградська -1.0  56.00  35.150288  36.215
Львівська      -1.0  63.88  36.462500  38.200
Полтавська     -1.0  51.07  34.973942  38.040